# Minimal cloudbuild.yaml without options section
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/customer-care-ai:latest', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-care-ai:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'customer-care-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/customer-care-ai:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5005'
      - '--set-env-vars'
      - 'PORT=5005'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/customer-care-ai:latest'

# Timeout after 20 minutes
timeout: 1200s

# Tags for the build
tags:
  - 'customer-care-ai'
  - 'cloud-run'
