steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:latest',
      '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
      '--build-arg', 'PROJECT_ID=$PROJECT_ID',
      '--build-arg', 'SHORT_SHA=${COMMIT_SHA:0:7}',
      '.'
    ]
    id: 'build'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:$COMMIT_SHA'
    ]
    id: 'push'

  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:latest'
    ]
    id: 'push-latest'

# Configure logging options
options:
  logging: CLOUD_LOGGING_ONLY  # This resolves the logging requirement
  # Uncomment and update if you need to specify a service account
  # serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/[YOUR_SERVICE_ACCOUNT]@$PROJECT_ID.iam.gserviceaccount.com'
  # Uncomment to use a specific machine type
  # machineType: 'N1_HIGHCPU_8'

# Store images in Container Registry
images: [
  'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:$COMMIT_SHA',
  'gcr.io/$PROJECT_ID/github.com/arslanmit/customer-care-ai:latest'
]

# Timeout for the build (in seconds)
timeout: 1800s  # 30 minutes

# Add substitutions that can be used in build steps
substitutions:
  _SERVICE_NAME: 'customer-care-ai'
  _REGION: 'europe-west1'  # Update this to your preferred region

# Add tags for better organization
tags: 
  - 'rasa'
  - 'customer-care-ai'
  - 'production'
