# Configure build options
options:
  # Use regional user-owned bucket for build logs
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    args: 
      - 'build'
      - '--network=cloudbuild'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/customer-care-ai:$COMMIT_SHA'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/customer-care-ai:latest'
      - '.'
    # Cache Docker layers
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-care-ai:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/customer-care-ai:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'customer-care-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/customer-care-ai:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5005'
      - '--set-env-vars'
      - 'PORT=5005'
      - '--revision-suffix'
      - '$SHORT_SHA'
      - '--quiet'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/customer-care-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/customer-care-ai:latest'

# Timeout after 20 minutes
timeout: 1200s

# Tags for the build
tags:
  - 'customer-care-ai'
  - 'cloud-run'

# Available substitutions:
# - $PROJECT_ID: The Google Cloud project ID
# - $COMMIT_SHA: The commit SHA that triggered the build
# - $SHORT_SHA: First 7 characters of the commit SHA
