version: "3.9"
services:
  rasa-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    # Backend is reachable at http://rasa-backend:5005 from other containers
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - REACT_APP_RASA_URL=http://localhost:5005
    depends_on:
      - rasa-backend
