services:
  # Rasa Core Service
  rasa:
    image: rasa/rasa:3.6.21-full
    command: ["run", "--enable-api", "--debug", "--cors", "*", "--credentials", "/app/credentials.yml", "--endpoints", "/app/endpoints.yml", "--model", "/app/models/20250625-022246-allegro-partition.tar.gz"]
    ports:
      - "5005:5005"
    volumes:
      - ./backend/rasa/models:/app/models
      - ./backend/rasa/config.yml:/app/config.yml
      - ./backend/rasa/domain.yml:/app/domain.yml
      - ./backend/rasa/endpoints.yml:/app/endpoints.yml
      - ./backend/rasa/credentials.yml:/app/credentials.yml
      - ./backend/rasa:/app/data
    environment:
      - RASA_ENVIRONMENT=production
      - RASA_TELEMETRY_ENABLED=false
      - RASA_ACTIONS_URL=http://actions:5055/webhook
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - rasa-network

  # Rasa Actions Server
  actions:
    image: rasa/rasa-sdk:3.6.0
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_ACTIONS_SANIC_WORKERS=2
    expose:
      - "5055"
    restart: unless-stopped
    networks:
      - rasa-network
      
  # Web Interface
  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./web-interface:/app
    restart: unless-stopped
    networks:
      - rasa-network
    depends_on:
      - rasa

networks:
  rasa-network:
    driver: bridge
