services:
  # Rasa Core Service
  rasa:
    image: rasa/rasa:3.6.21-full
    command: run --enable-api --model /app/models --endpoints /app/endpoints.yml --credentials /app/credentials.yml
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./backend/rasa/config.yml:/app/config.yml
      - ./backend/rasa/domain.yml:/app/domain.yml
      - ./backend/rasa/endpoints.yml:/app/endpoints.yml
      - ./backend/rasa/credentials.yml:/app/credentials.yml
      - ./backend/rasa:/app/data
    environment:
      - RASA_ENVIRONMENT=production
      - RASA_TELEMETRY_ENABLED=false
      - RASA_ACTIONS_URL=http://actions:5055/webhook
    restart: unless-stopped
    networks:
      - rasa-network

  # Rasa Actions Server
  actions:
    image: rasa/rasa-sdk:3.13.0rc1-latest
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_ACTIONS_SANIC_WORKERS=2
    expose:
      - "5055"
    restart: unless-stopped
    networks:
      - rasa-network


networks:
  rasa-network:
    driver: bridge
