version: "3"

services:
  # Rasa Core Service
  rasa:
    image: rasa/rasa:3.6.21-full
    command: rasa run --enable-api --debug --credentials /app/credentials.yml --endpoints /app/endpoints.yml
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./backend/rasa/config.yml:/app/config.yml
      - ./backend/rasa/domain.yml:/app/domain.yml
      - ./backend/rasa/endpoints.yml:/app/endpoints.yml
      - ./backend/rasa/credentials.yml:/app/credentials.yml
      - ./backend/rasa:/app/data
    environment:
      - RASA_ENVIRONMENT=production
      - RASA_TELEMETRY_ENABLED=false
      - RASA_ACTIONS_URL=http://actions:5055/webhook
      # RASA_MODEL_PATH must be provided when starting the container
    restart: unless-stopped
    networks:
      - rasa-network

  # Rasa Actions Server
  actions:
    image: rasa/rasa-sdk:3.6.0
    volumes:
      - ./actions:/app/actions
    environment:
      - RASA_ACTIONS_SANIC_WORKERS=2
    expose:
      - "5055"
    restart: unless-stopped
    networks:
      - rasa-network
      
  # Web Interface
  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./web-interface:/app
    restart: unless-stopped
    networks:
      - rasa-network
    depends_on:
      - rasa

networks:
  rasa-network:
    driver: bridge
