version: "3.8"
services:
  rasa-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5005:5005"
    environment:
      - RASA_ENVIRONMENT=development
    command: python run.py --enable-api --cors "*" --debug-backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - REACT_APP_RASA_URL=http://localhost:5005
    depends_on:
      - rasa-backend
