version: "3.1"
language: en

# NLU Pipeline Configuration
pipeline:
  # Text processing
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: "mean"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  
  # Intent classification
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: "softmax"
  
  # Entity extraction
  - name: EntitySynonymMapper
  
  # Fallback handling
  - name: FallbackClassifier
    threshold: 0.4  # Confidence threshold for fallback
    ambiguity_threshold: 0.1  # Minimum difference between top two intents

# Policies Configuration
policies:
  # Rule-based policies
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
  
  # Machine learning policy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    batch_size: [32, 64]
    learning_rate: 0.001
    hidden_layers_sizes:
      text: [256, 128]
    number_of_attention_heads: 4
    key_relative_attention: true
    max_relative_position: 5
    use_key_relative_attention: true
    use_max_neg_sim: true
    use_gelu: true
    drop_rate: 0.1
    drop_rate_attention: 0.1
    weight_sparsity: 0.8
  
  # Memorization policy
  - name: MemoizationPolicy
    max_history: 5
    lookup:
      - text
      - intent
      - entities

# Fallback configuration
assistant_id: customer-care-ai-$(shell date +%s)

# Session configuration
session_config:
  session_expiration_time: 60  # minutes
  carry_over_slots_to_new_session: true

# Response selector fallback configuration
response_retrieval:
  fallback_action_name: "action_default_fallback"
  retrieval_intent: "out_of_scope"
