global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert.rules'
  # - "first_rules.yml"
  # - "second_rules.yml"

# Remote write configuration for Grafana Cloud
remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: "277116"
      password: "glc_eyJvIjoiNTc2NDI4IiwibiI6InN0YWNrLTI4ODYxMS1obS1yZWFkLWN1c3RvbWVyLWNhcmUtYWkiLCJrIjoiSDQ0NkU5bUFPeDd5OTUzZFlsRzdWb3EyIiwibSI6eyJyIjoidXMifX0="
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'up|process_.*|prometheus_.*|puma_.*|rack_.*|rails_.*|ruby_.*|sidekiq_.*|redis_.*|resque_.*|http_.*|node_.*|go_.*|process_cpu_seconds_total|process_open_fds|process_resident_memory_bytes|process_start_time_seconds|process_virtual_memory_bytes|process_max_fds'
        action: keep

# Scrape configurations for Prometheus
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Rasa Server metrics
  - job_name: 'rasa'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rasa:5005']
    scrape_interval: 5s
    scrape_timeout: 4s

  # Rasa Actions Server metrics
  - job_name: 'rasa-actions'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['actions:5055']
    scrape_interval: 5s
    scrape_timeout: 4s

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'redis-exporter:9121'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']

  # Blackbox exporter for HTTP/HTTPS checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://rasa:5005/version  # Rasa server
          - http://actions:5055/     # Rasa actions
          - http://frontend:3000     # Frontend
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __metrics_path__
        regex: (.+)/metrics
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'
