version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
  case_sensitive: false
- name: LexicalSyntacticFeaturizer
  features:
  - - low
    - pos
  - - BOS
    - EOS
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: "softmax"
  hidden_layer_sizes:
    text: [256, 128]
  batch_size: [32, 64]
  learning_rate: 0.001
  use_masked_language_model: true
  weight_sparsity: 0.8
  drop_rate: 0.1
  drop_rate_attention: 0.1
  use_gelu: true
  use_key_relative_attention: true
  max_relative_position: 5
  number_of_attention_heads: 4
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1
- name: ResponseSelector
  epochs: 100
  retrieval_intent: "faq"
  hidden_layer_sizes:
    text: [256, 128]
  batch_size: [32, 64]
  learning_rate: 0.001

policies:
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 8
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  hidden_layer_sizes:
    text: [256, 128]
    action: [64]
  number_of_attention_heads: 4
  dropout: 0.2
  weight_sparsity: 0.8
  use_gpu: false
  use_key_relative_attention: true
  use_max_neg_sim: true
  use_gelu: true
  drop_rate: 0.1
  drop_rate_attention: 0.1
  max_relative_position: 10
  constrain_similarities: true
  model_confidence: "softmax"

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

# assistant_id: customer-care-ai
assistant_id: latest_rasa_model