name: customer-care-ai-trigger
description: "Build and deploy to Cloud Run on push to main branch"
github:
  name: customer-care-ai
  owner: arslanmit
  push:
    branch: '^main$'
filename: cloudbuild.yaml
serviceAccount: projects/customer-care-ai-463420/serviceAccounts/customer-care-ai-463420@appspot.gserviceaccount.com
substitutions:
  _SERVICE_NAME: customer-care-ai
  _REGION: europe-west1
