name: CI Tests
on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  frontend-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci --ignore-scripts

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --watchAll=false

  backend-tests:
    name: Backend Rasa Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install project dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rasa tests (stories & actions)
        run: |
          source venv/bin/activate
          rasa test --no-prompt

  deploy:
    name: Build & Push Docker Images
    if: github.ref == 'refs/heads/main'
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Authenticate Docker to gcr.io
        run: gcloud auth configure-docker --quiet

      - name: Build & push backend image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/rasa-backend:${{ github.sha }} -f Dockerfile .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/rasa-backend:${{ github.sha }}

      - name: Build & push frontend image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/chat-frontend:${{ github.sha }} -f frontend/Dockerfile ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/chat-frontend:${{ github.sha }}

      - name: Deploy updated images to Cloud Run
        env:
          PROJECT: ${{ secrets.GCP_PROJECT }}
          REGION: ${{ secrets.GCP_REGION }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          # Deploy backend
          gcloud run deploy rasa-backend \
            --image gcr.io/$PROJECT/rasa-backend:${{ github.sha }} \
            --region $REGION --platform managed --quiet

          # Deploy frontend with backend URL env var
          gcloud run deploy chat-frontend \
            --image gcr.io/$PROJECT/chat-frontend:${{ github.sha }} \
            --region $REGION --platform managed --quiet \
            --update-env-vars REACT_APP_RASA_URL=$BACKEND_URL
