name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install backend dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    # Install frontend dependencies
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    # Build frontend
    - name: Build frontend
      working-directory: frontend
      env:
        VITE_API_URL: ${{ vars.API_URL || 'https://api.yourdomain.com' }}
        VITE_RASA_URL: ${{ vars.RASA_URL || 'https://rasa.yourdomain.com' }}
      run: |
        npm run build

    # Deploy to your infrastructure (example: Vercel, AWS, etc.)
    - name: Deploy application
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        # Add other required secrets here
      run: |
        # Add your deployment commands here
        # Example:
        # ./deploy.sh
        echo "Deployment would happen here"

    # Health check
    - name: Verify deployment
      run: |
        # Add health check for your services
        echo "Verifying services are up..."
        # curl -sSf ${{ vars.API_URL }}/health || exit 1
        # curl -sSf ${{ vars.RASA_URL }}/webhooks/rest/webhook/health || exit 1
