name: Performance Test

on:
  workflow_dispatch:
    inputs:
      users:
        description: 'Number of virtual users'
        required: false
        default: '100'
      duration:
        description: 'Test duration (e.g., 30s, 5m)'
        required: false
        default: '1m'
      environment:
        description: 'Environment to test against'
        required: false
        default: 'staging'

jobs:
  k6-test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: k6/script.js
          cloud: true
          projectID: ${{ vars.K6_CLOUD_PROJECT_ID }}
          token: ${{ secrets.K6_CLOUD_TOKEN }}
          vus: ${{ github.event.inputs.users || 100 }}
          duration: ${{ github.event.inputs.duration || '1m' }}
          
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: k6/results
